"""add emotion and liveness fields

Revision ID: 65edcce9b9c0
Revises: 20260730_0002
Create Date: 2026-07-30 14:23:13.947514
"""
from typing import Sequence, Union

revision: str = '65edcce9b9c0'
down_revision: Union[str, None] = '20260730_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
