"""add user memory facts and voice gender preference

Revision ID: e100ba107f49
Revises: 20260731_0003
Create Date: 2026-08-03 13:37:04.579010
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e100ba107f49'
down_revision: Union[str, None] = '20260731_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

